name: Publish configs
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        inputs:
            env:
                description: DFB environment
                required: false
                type: choice
                default: ALL
                options:
                    - ALL
                    - PROD
                    - STAG
                    - TEST
                    - DEV
            region:
                description: DFB region
                required: false
                type: choice
                default: ALL
                options:
                    - ALL
                    - EU-CENTRAL-1
                    - AP-NORTHEAST-1

env:
  PROJECT_NAME: Dazn.Orders.Config
  DOCKER_IMAGE: ${{ github.event.repository.name }}/config-sync:${{ github.sha }}

jobs:
    publish-configs:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:

            - name: Checkout
              uses: actions/checkout@v2

            - name: Ensure scripts are executable
              run: find ./scripts -type f \( -name "*.ps1" -or -name "*.sh" \) -print0 | xargs -0 chmod 755

            - name: Build Docker
              run: docker build -t ${{ env.DOCKER_IMAGE }} -f ./config-sync/Dockerfile .

            - name: DEV - Configure AWS credentials
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'DEV' || github.event.inputs.env == 'ALL' }}
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1
                role-to-assume: arn:aws:iam::714306903482:role/automation-gha-ci

            - name: DEV - Publish configs
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'DEV' || github.event.inputs.env == 'ALL' }}
              uses: ./.github/actions/publish
              with:
                env: DEV
                region: ${{ github.event.inputs.region  || 'ALL' }}

            - name: TEST - Configure AWS credentials
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'TEST' || github.event.inputs.env == 'ALL' }}
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1
                role-to-assume: arn:aws:iam::931209822253:role/automation-gha-ci

            - name: TEST - Publish configs
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'TEST' || github.event.inputs.env == 'ALL' }}
              uses: ./.github/actions/publish
              with:
                env: TEST
                region: ${{ github.event.inputs.region  || 'ALL' }}

            - name: STAG - Configure AWS credentials
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'STAG' || github.event.inputs.env == 'ALL' }}
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1
                role-to-assume: arn:aws:iam::175901229741:role/automation-gha-ci

            - name: STAG - Publish configs
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'STAG' || github.event.inputs.env == 'ALL' }}
              uses: ./.github/actions/publish
              with:
                env: STAG
                region: ${{ github.event.inputs.region  || 'ALL' }}

            - name: PROD - Configure AWS credentials
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'PROD' || github.event.inputs.env == 'ALL' }}
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-central-1
                role-to-assume: arn:aws:iam::556548779709:role/automation-gha-ci

            - name: PROD - Publish configs
              if: ${{ !github.event.inputs.env || github.event.inputs.env == 'PROD' || github.event.inputs.env == 'ALL' }}
              uses: ./.github/actions/publish
              with:
                env: PROD
                region: ${{ github.event.inputs.region  || 'ALL' }}

            - name: Success
              run: echo "### Success successful published on _${{ github.event.inputs.env || 'ALL' }}_ | _${{ github.event.inputs.region || 'ALL' }}_ :rocket:" >> $GITHUB_STEP_SUMMARY

